### ISSUE TITLE
Not getting pipeline messages

### ISSUE THREAD

**Issue by sesinando2** [jenkins-x-plugins/jx-slack#28]
I'm trying to setup slack integration on jx3 following this guide. https://jenkins-x.io/v3/develop/ui/slack/#configuring-slack-notifications,

I've already create the slack app and added it to a channel.
![image](https://user-images.githubusercontent.com/5663734/110635897-bb108e00-81ff-11eb-8b73-5e10fc9f62c5.png)
![image](https://user-images.githubusercontent.com/5663734/110635978-d24f7b80-81ff-11eb-866d-01508b314b6b.png)

I've also configured slack in `source-config.yaml` and tried it in multiple levels:

```
apiVersion: gitops.jenkins-x.io/v1alpha1
kind: SourceConfig
metadata:
  creationTimestamp: null
spec:
  groups:
  - owner: Ibenta
    provider: https://github.com
    providerKind: github
    repositories:
    - name: springboot-template
      slack:
        channel: '#jenkins-x-pipelines'
        kind: all
        pipeline: all
    - name: stencil
      slack:
        channel: '#jenkins-x-pipelines'
        kind: all
        pipeline: all
    scheduler: in-repo
    slack:
      channel: '#jenkins-x-pipelines'
      kind: all
      pipeline: all
  slack:
    channel: '#jenkins-x-pipelines'
    kind: all
    pipeline: all
```
and the slack pod is already up and running

```
kubectl get pod -l app=jx-slack
NAME                        READY   STATUS    RESTARTS   AGE
jx-slack-686968776d-dnmtw   1/1     Running   0          3h3m
```

But i'm still not receiving the notifications. Looking at the logs there's no error. But it did say there's no config for some of my pipelines.

```
kubectl logs -f jx-slack-686968776d-dnmtw                         
using driver: github and serverURL: https://github.com
wrote git credentials file /root/.git-credentials
about to run: git clone https://github.com/Ibenta/cluster-gitops.git /tmp/jx-git-835694998 in dir /tmp
Cloning into '/tmp/jx-git-835694998'...
about to run: git clone https://github.com/Ibenta/cluster-gitops.git /tmp/jx-git-236991485 in dir /tmp
Cloning into '/tmp/jx-git-236991485'...
W0310 10:16:25.408991       1 warnings.go:70] extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
using the dashboard URL http://dashboard-jx.gitops.ibenta.com
Watching slackbots in namespace jx
Watching pipeline activities in namespace jx and slackbot config 
no slack configuration for ibenta-cluster-gitops-master-3
no slack configuration for ibenta-stencil-head-1
no slack configuration for ibenta-cluster-gitops-master-6
no slack configuration for ibenta-cluster-gitops-master-7
```

I also don't see any slackbot crds  and resources in my cluster as stated in the readme.

```
kubectl get crd -A | grep jenkins        
environments.jenkins.io                      2021-03-08T12:39:51Z
lighthousejobs.lighthouse.jenkins.io         2021-03-08T12:39:52Z
pipelineactivities.jenkins.io                2021-03-08T12:39:52Z
previews.preview.jenkins.io                  2021-03-08T12:39:52Z
releases.jenkins.io                          2021-03-08T12:39:52Z
sourcerepositories.jenkins.io                2021-03-08T12:39:52Z
```

```
k get SlackBot             
error: the server doesn't have a resource type "SlackBot"
```

Any idea what the issue is? Or any tips to debug this further?
