### ISSUE TITLE
Direct Message Reviewers Feature not working

### ISSUE THREAD

**Issue by rishka** [jenkins-x-plugins/jx-slack#38]
Installed the latest version of this application to my jx3 cluster, but I am unable to trigger direct messages to requested reviewers

According to the logs it prepares the review request message, but it never sends it. 

I do not have a user mapping setup as it was removed from the chart, but I am also not getting any errors that it is unable to find the user. 

I used this to set it up
```
      slack:
        channel: '#jx-pipelines'
        kind: failureOrNextSuccess
        pipeline: all
        notifyReviewers: "true"
        directMessage: "true"
```
